### PR TITLE
Bump `starknet` to `0.12.0`

### LINKED ISSUE #2452: Remove patches from `Cargo.toml`
Due to custom patches

https://github.com/dojoengine/dojo/blob/5777c0076576de369bba7fe9ffd73abe38447dd3/Cargo.toml#L248-L253

this is difficult to integrate Dojo as package due to dependency issues.

With the recent bump of `starknet` to 0.12 https://github.com/xJonathanLEI/starknet-rs/pull/655 maybe we could bump the dependency.

https://github.com/xJonathanLEI/starknet-rs/pull/657 should also be useful to remove all the patches as per this comment

https://github.com/dojoengine/dojo/blob/5777c0076576de369bba7fe9ffd73abe38447dd3/Cargo.toml#L242-L245

### PR DESCRIPTION
**Pull request by kariy**
resolves #2452 

- bump `starknet` to `0.12.0`
- bump `starknet-types-core` to `0.1.6`

## Summary by CodeRabbit

- **New Features**
	- Introduced a new asynchronous method for handling multiple JSON-RPC requests, enhancing batch request capabilities.

- **Bug Fixes**
	- Updated various dependencies to improve stability and compatibility, including major upgrades for `starknet` and `alloy-*` libraries.

These changes focus on enhancing the application's performance and reliability for end-users.

### CODE REVIEW

**Comment by tcoratger** [comment]
@kariy 
- I think we can bump cainome with the new release https://github.com/cartridge-gg/cainome/releases/tag/v0.4.1
- I'm trying to obtain a new release of `starknet-types-core` so that we can remove all patches

**Comment by kariy** [comment]
> @kariy
> 
> * I think we can bump cainome with the new release https://github.com/cartridge-gg/cainome/releases/tag/v0.4.1

yup, 

> * I'm trying to obtain a new release of `starknet-types-core` so that we can remove all patches

yes pls. would very much appreciate that

**Comment by kariy** [comment]
@tcoratger the pr is pretty much ready except for the `starnet-types-core` release. will defer merging until the release is out.

**Comment by tcoratger** [comment]
> @tcoratger the pr is pretty much ready except for the `starnet-types-core` release. will defer merging until the release is out.

@kariy sure will post a message here once I've a release

**Comment by tcoratger** [comment]
@kariy should be done here https://github.com/starknet-io/types-rs/pull/95

**Comment by tcoratger** [comment]
@kariy Cool thanks a lot for this, is it possible to merge asap because this is blocking for us at Kakarot :) ?

**Review by tcoratger — APPROVED** [review]

**Comment by kariy** [comment]
> @kariy Cool thanks a lot for this, is it possible to merge asap because this is blocking for us at Kakarot :) ?

Ahh sorry. The Windows build is still breaking but didn't have enough time to debug it today. Will get it merged first thing tomorrow!

**Pull request merged**
