### PR TITLE
feat(sozo): support for dev mode with hot reloading

### PR DESCRIPTION
**Pull request by lambda-0x**
continuation of #827

### CODE REVIEW

**Comment by ptisserand** [comment]
Hi @lambda-0x, previous behavior was the same as `sozo build` and then `sozo migrate`.

Could you please check if `sozo migrate` find any differences after you apply the same cairo code modification ?

**Comment by lambda-0x** [comment]
idk how sozo migrate works but for me doing `sozo migrate` always shows there are 7 diffs and tries to deploy all of them everytime, even before this PR.

**Comment by kariy** [comment]
> and tries to deploy all of them everytime, even before this PR.

that is only if you don't specify the remote world address, `--world`. 

if specified, it will compute the proper diff. Otherwise, if the arg is not specified, it will attempt to deploy everything, thus, showing all diffs.

**Comment by lambda-0x** [comment]
gotcha, will retry then.

**Comment by ptisserand** [comment]
@lambda-0x it seems to be fine.

Your branch has the same behavior as mine:

- Start katana
- Start sozo dev in example/ecs with the following command:
```
/workspaces/dojo/target/debug/sozo dev --name bob
```
- After I add a `dummy` field in `Moves` (component.cairo), rebuild and migration is done:
```
📦 Rebuild done
Total diffs found: 3
[3] 📦 Preparing for migration....
  > Total items to be migrated (3): New 0 Update 3
  
# Components (1)
Moves
  > class hash: 0x5ed48dfb49006a05ca8ee754250cab811cea38f81d32951a6b2c73342eab1ff
# Systems (2)
spawn
  > class hash: 0x2a6e7c2d79fd728ee5965190fab2054991ae54695065bdd7f23fd02eb486eb9
move
  > class hash: 0xa667ef46f6074a95edeaff265b912b1f19366351a09fd0aa4aa4713fb5f1b4

🎉 Successfully migrated World at address 0x64773f2f8864b5a793ab3ebe4fa169ec950b275cc00b7276c77d440f93f3f4f
🎉 World at address 0x64773f2f8864b5a793ab3ebe4fa169ec950b275cc00b7276c77d440f93f3f4f updated!
```

**Comment by lambda-0x** [comment]
oh gotcha, i was trying to update implementation of `PositionTrait` which didn't create a diff because its not used (because of cairo compiler removing unused code).

**Comment by lambda-0x** [comment]
This is ready for review then

**Pull request merged**
