### PR TITLE
refactor(sozo-migrate): set migrator account block to `pending`

### PR DESCRIPTION
**Pull request by kariy**

### CODE REVIEW

**Comment by kariy** [comment]
@tarrencev do you think there would be any unwanted behaviour because of this? because we're basing all the read request to `pending` state now.

**Comment by tarrencev** [comment]
Hmm this just sets all requests to pending? Executes included? Should be fine. I'm pretty sure 0.12 is removing pending though. Not sure what the plan with the rpc is. cc @xJonathanLEI

**Comment by kariy** [comment]
> Hmm this just sets all requests to pending? Executes included? Should be fine. I'm pretty sure 0.12 is removing pending though. Not sure what the plan with the rpc is. cc @xJonathanLEI

v0.12 only removes the `pending` tx status, no? but `pending` block will still exists. https://docs.starknet.io/documentation/starknet_versions/upcoming_versions/#removal_of_pending_status

**Comment by xJonathanLEI** [comment]
@kariy is right. Pending block still exists. It's actually funnier than that. So with tx status `PENDING` gone you end up with `ACCEPTED_ON_L2` txs that are _in fact_ `PENDING` because they live in the `PENDING` block and has no block hash when queried.

**Comment by tarrencev** [comment]
> @kariy is right. Pending block still exists. It's actually funnier than that. So with tx status `PENDING` gone you end up with `ACCEPTED_ON_L2` txs that are _in fact_ `PENDING` because they live in the `PENDING` block and has no block hash when queried.

Ah I see. A bit confusing lol. Either way I think this change is good, we always want to operate against the most up to date sequencer state

**Review by tarrencev — APPROVED** [review]

**Pull request merged**
