### PR TITLE
fix: add missing delete event

### PR DESCRIPTION
**Pull request by sparqet**

### CODE REVIEW

**Comment by milancermak** [comment]
Looking good.

Since this PR is already touching the delete event, can you also change the `tableId` to `table_id` in the event declaration itself please?

**Comment by sparqet** [comment]
@milancermak done ✅

**Comment by milancermak** [comment]
Sorry, it's supposed to be the other way around. `table_id` is the right one we want, `tableId` is 👎

**Comment by sparqet** [comment]
Oh sorry I misunderstood haha

**Review by milancermak — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
