### PR TITLE
[dojo-core] use const array for pow2

### LINKED ISSUE #1859: [dojo-core] replace `fpow` fn with const span
**Is your feature request related to a problem? Please describe.**
cairo 2.6.0 allow declaring const span which should be more efficient than computing value

**Describe the solution you'd like**
replace `fpow` fn with const span in packing.cairo
https://github.com/dojoengine/dojo/blob/d1604796a253d3f9408e37df0c32e81c8a7d894d/crates/dojo-core/src/packing.cairo#L142

### PR DESCRIPTION
**Pull request by notV4l**
this should work with next scarb version and be way cheaper

closes #1859

### CODE REVIEW

**Comment by glihm** [comment]
> this should work with next scarb version and be way cheaper
> 
> closes #1859

When you say next version, `2.6` or `2.7`?

**Comment by notV4l** [comment]
> > this should work with next scarb version and be way cheaper
> 
> > 
> 
> > closes #1859
> 
> 
> 
> When you say next version, `2.6` or `2.7`?

it works with current scarb nigthly

**Comment by glihm** [comment]
@notV4l this one should now work correctly targeting the `storage_layout` branch. Will check that during this week and change the base branch. 👍

**Review by glihm — APPROVED** [review]
Good anticipation @notV4l, very good optimization.

**Pull request merged**
