### PR TITLE
fix(sozo): ensure warnings don't stop tests build

### PR DESCRIPTION
**Pull request by glihm**
Closes DOJ-252, #1646.

### CODE REVIEW

**Comment by kariy** [comment]
hmm im still getting the reported error even with with this change

**Comment by glihm** [comment]
> hmm im still getting the reported error even with with this change

With which project did you try? Do you have only warnings?
I'll add tests tomorrow, that's a good point.

But I've tested on `spawn-and-move` and I have the expected output:
image

**Comment by kariy** [comment]
> > hmm im still getting the reported error even with with this change
> 
> With which project did you try? Do you have only warnings? I'll add tests tomorrow, that's a good point.
> 
> But I've tested on `spawn-and-move` and I have the expected output: image

ah nvm my mistake.. its working lol

**Review by kariy — APPROVED** [review]

**Comment by glihm** [comment]
As discussed this morning, the rework of sozo `ops` and `commands` will address related tests.

**Pull request merged**
