### PR TITLE
Add starkscan-verifier to migration

### PR DESCRIPTION
**Pull request by Matth26**
Related to issue #208

### CODE REVIEW

**Comment by tarrencev** [comment]
this looks great!

**Comment by Matth26** [comment]
I've tested the code in a separate Rust project. Everything is working, except for the fact that starkscan-verifier doesn't handle Cairo1 contracts yet.

I'm currently searching for the best place to insert the `verify_class` call. Should I add it in the `/migration/mod.rs` as a method of the `Migration` struct?

**Comment by ponderingdemocritus** [comment]
@Matth26 are you still planning on completing this?

**Comment by Matth26** [comment]
> @Matth26 are you still planning on completing this?
@ponderingdemocritus currently starkscan-verifier doesn't support cairo1 verifying. I'm going to ask the starkscan team if they plan to update it soon.

**Comment by Matth26** [comment]
ETA has been asked on the starkscan-verifier repo, but no answer so far
https://github.com/starkscan/starkscan-verifier/issues/8

If you want to clean PR you can close it and I'll reopen it when api is working

**Pull request closed without merging**
