### PR TITLE
feat(katana): add support to declare V1 (#385)

### PR DESCRIPTION
**Pull request by ptisserand**
This PR add support to declare V1 transaction.
I have added a unit test similar to the declare V2 transaction one but I'm not sure if this test is enough.

Closes: #385

### CODE REVIEW

**Review by kariy — COMMENTED** [review]
Can you also copy the implementation into [`estimate_fee`](https://github.com/dojoengine/dojo/blob/d70f9c4b8bcbcfef89f0fd0cfa3f23b611bcbddd/crates/katana-rpc/src/starknet/mod.rs#L696) ? its a bit messy and a lot of redundancy atm but will sort out later

**Comment by ptisserand** [comment]
> Can you also copy the implementation into [`estimate_fee`](https://github.com/dojoengine/dojo/blob/d70f9c4b8bcbcfef89f0fd0cfa3f23b611bcbddd/crates/katana-rpc/src/starknet/mod.rs#L696) ? its a bit messy and a lot of redundancy atm but will sort out later

I  have copied the implementation into `estimate_fee`

Do  you mean redundancy in my implementation or in duplicated code between `estimate_fee` and `add_declare_transaction` ?

**Comment by kariy** [comment]
> > Can you also copy the implementation into [`estimate_fee`](https://github.com/dojoengine/dojo/blob/d70f9c4b8bcbcfef89f0fd0cfa3f23b611bcbddd/crates/katana-rpc/src/starknet/mod.rs#L696) ? its a bit messy and a lot of redundancy atm but will sort out later
> 
> I have copied the implementation into `estimate_fee`
> 
> Do you mean redundancy in my implementation or in duplicated code between `estimate_fee` and `add_declare_transaction` ?

the latter

**Review by kariy — APPROVED** [review]
lgtm. just need to pass the checks

**Comment by ptisserand** [comment]
> lgtm. just need to pass the checks

Should be ok now:
`$ ./scripts/rust_fmt.sh` returns 0

**Pull request merged**
