### PR TITLE
update dead links

### PR DESCRIPTION
**Pull request by taikoonwang**
# Description

this PR fix issue's part 1. for part 2, I think the proper way to do this is to add a readme, so it's outside the scope of the dead link.

## Related issue
https://github.com/dojoengine/dojo/issues/2035

## Tests

- [ ] Yes
- [ ] No, because they aren't needed
- [ ] No, because I need help

## Added to documentation?

- [ ] README.md
- [ ] [Dojo Book](https://github.com/dojoengine/book)
- [ ] No documentation needed

## Checklist

- [ ] I've formatted my code (`scripts/prettier.sh`, `scripts/rust_fmt.sh`, `scripts/cairo_fmt.sh`)
- [ ] I've linted my code (`scripts/clippy.sh`, `scripts/docs.sh`)
- [ ] I've commented my code
- [ ] I've requested a review after addressing the comments

### CODE REVIEW

**Comment by glihm** [comment]
Hey @taikoonwang good catch.

| for part 2, I think the proper way to do this is to add a readme, so it's outside the scope of the dead link.

Could you detail that?

Also, would you mind fixing the dojoup README link?

**Comment by taikoonwang** [comment]
> Hey @taikoonwang good catch.
> 
> | for part 2, I think the proper way to do this is to add a readme, so it's outside the scope of the dead link.
> 
> Could you detail that?
> 
> Also, would you mind fixing the dojoup README link?

I mean I have no idea how to fix https://book.dojoengine.org/toolchain/dojoup (which is borken),If we just change it to https://book.dojoengine.org/toolchain (which is also borken), Because the whole toolchain missing an overview readme. 

image source:

**Comment by glihm** [comment]
@taikoonwang got you, thanks for the explanation.
You're right before we had a dedicated section for `dojoup`. But `asdf` is simplifying the management of several versions and different installation sources.

**Review by glihm — APPROVED** [review]
Thanks for those fixes @taikoonwang. 🙏

**Pull request merged**
