### PR TITLE
feat: add transaction_hash and block_number in the manifest file

### PR DESCRIPTION
**Pull request by remybar**
Related to: https://github.com/dojoengine/dojo/issues/748

For the world and every deployed contracts, store the `transaction_hash` and the `block_number` of the transaction which deploys them.

Pending points:
- [ ] Currently, the deployment manifest file is created by merging the `base`, `overlay` and `remote` manifest files, replacing the old deployment manifest file.
  `transaction_hash` and `block_number` data are collected during migration, so they are stored in the deployment manifest only. I don't think they are easily retrievable from the remote manifest (i.e from the blockchain) so we should also merge the old deployment manifest file with the other manifests as a starting point of the migration to avoid losing `transaction_hash` and `block_number` of not updated contracts.
- [ ] stored the `seed` used to create the world. It looks like the seed is just the name of the world, and the name is already stored. So, did I miss something for this point ?

@glihm @tarrencev
what is your opinion about these 2 pending points ?

### CODE REVIEW

**Comment by lambda-0x** [comment]
Thank you for your contribution!

To answer few of your questions:

> Currently, the deployment manifest file is created by merging the base, overlay and remote manifest files, replacing the old deployment manifest file.

we merge `base` with `overlay` to get the manifest that requires to be deployed. `remote` manifest is [used calculate](https://github.com/dojoengine/dojo/blob/88bae9f436acbf0325de27be68264aff979dce40/bin/sozo/src/ops/migration/mod.rs#L75) `WorldDiff` which represents what we actually need to deploy.

> also merge the old deployment manifest file with the other manifests as a starting point of the migration to avoid losing transaction_hash and block_number of not updated contracts.

yeah i think that makes sense to me, wdyt @tarrencev 

>  stored the seed used to create the world. It looks like the seed is just the name of the world, and the name is already stored. So, did I miss something for this point ?

what we used to called `seed` is now called `name` in `sozo migrate` subcommand, by default its the [name of project in `Scarb.toml`](https://github.com/dojoengine/dojo/blob/88bae9f436acbf0325de27be68264aff979dce40/examples/spawn-and-move/Scarb.toml#L3) but user can specify custom name (seed) as well

**Comment by lambda-0x** [comment]
@remybar also we need `transaction_hash` and `block_number` only for `world` contract so you can remove it for other contracts

**Comment by remybar** [comment]
> Thank you for your contribution!
> 
> To answer few of your questions:
> 
> > Currently, the deployment manifest file is created by merging the base, overlay and remote manifest files, replacing the old deployment manifest file.
> 
> we merge `base` with `overlay` to get the manifest that requires to be deployed. `remote` manifest is [used calculate](https://github.com/dojoengine/dojo/blob/88bae9f436acbf0325de27be68264aff979dce40/bin/sozo/src/ops/migration/mod.rs#L75) `WorldDiff` which represents what we actually need to deploy.
> 
> > also merge the old deployment manifest file with the other manifests as a starting point of the migration to avoid losing transaction_hash and block_number of not updated contracts.
> 
> yeah i think that makes sense to me, wdyt @tarrencev
> 
> > stored the seed used to create the world. It looks like the seed is just the name of the world, and the name is already stored. So, did I miss something for this point ?
> 
> what we used to called `seed` is now called `name` in `sozo migrate` subcommand, by default its the [name of project in `Scarb.toml`](https://github.com/dojoengine/dojo/blob/88bae9f436acbf0325de27be68264aff979dce40/examples/spawn-and-move/Scarb.toml#L3) but user can specify custom name (seed) as well

Thank you @lambda-0x and @glihm for these details !

I have modified this PR to handle `transaction_hash` and `block_number` for the world contract only. 
I've also added a `merge_from_previous` method to `DeployedManifest` to be able to retrieve `transaction_hash` and `block_number` from an old deployment manifest.
I don't know if the name is good, but I wanted to avoid writing a global `merge` method that would have merged all the fields from `DeployedManifest` when we are only interested in 2 fields of the world contract at the moment.

Now, I have to deep more on the `seed`/`name` topic because I don't understand why the World contract is not migrated if we change its name (which is used as salt to generate its contract address).

**Comment by glihm** [comment]
Awesome work man.

> Now, I have to deep more on the seed/name topic because I don't understand why the World contract is not migrated if we change its name (which is used as salt to generate its contract address).

Not sure I get you here. If you run `sozo migrate --name world2` it seems the world is correctly migrated. And in your branch, the manifest is updated with new addresses. However the name is not updated in the deployment manifest (were you referring to that?).

**Comment by lambda-0x** [comment]
I think seed related changes require some discussion which might take some time, so we can merge this PR without those changes and tackle it in a different PR to unblock #1652. wdyt @glihm?

**Comment by glihm** [comment]
> I think seed related changes require some discussion which might take some time, so we can merge this PR without those changes and tackle it in a different PR to unblock #1652. wdyt @glihm?

Yep sounds good, I'll open an issue to follow up on that and discuss around the seed.

@remybar if you already have some work / research on the seed don't hesitate to comment on the issue. 👍

**Review by glihm — APPROVED** [review]
Thanks @remybar for the work done here, let's move to the next step, @lambda-0x stage is yours!

**Pull request merged**
