### PR TITLE
Upgrade rust to 1.74.0

### PR DESCRIPTION
**Pull request by fishseabowl**
This PR fixed the issue "Github Action for cargo-udeps failed" as mentioned in issue #1364

### CODE REVIEW

**Comment by glihm** [comment]
Hey @fishseabowl thanks for the contribution here!

Would appreciate your input on the discussion started on the issue. :+1: 

Fixes #1407.

**Review by kariy — CHANGES_REQUESTED** [review]
Don't forget to change it in the release ci as well

https://github.com/dojoengine/dojo/blob/3bb35a6790de3eea83e5c728ed0de46523a3de10/.github/workflows/release.yml#L11

**Comment by fishseabowl** [comment]
> Don't forget to change it in the release ci as well
> 
> https://github.com/dojoengine/dojo/blob/3bb35a6790de3eea83e5c728ed0de46523a3de10/.github/workflows/release.yml#L11

Thanks for your reminder. Has changed.

**Comment by fishseabowl** [comment]
Hello @kariy, could you please take a look at the reported errors? It mentions that: [= note: the `wasm32-unknown-unknown` target may not be installed](https://github.com/dojoengine/dojo/actions/runs/7477517467/job/20350592794?pr=1365) in `ci/ensure-wasm`, and [error: 'cargo-clippy' is not installed for the toolchain '1.74.0-x86_64-unknown-linux-gnu'](https://github.com/dojoengine/dojo/actions/runs/7477517467/job/20350589840?pr=1365) in `ci/clippy`, even though it's installed in the Dockerfile.

**Comment by glihm** [comment]
> Hello @kariy, could you please take a look at the reported errors? It mentions that: [= note: the `wasm32-unknown-unknown` target may not be installed](https://github.com/dojoengine/dojo/actions/runs/7477517467/job/20350592794?pr=1365) in `ci/ensure-wasm`, and [error: 'cargo-clippy' is not installed for the toolchain '1.74.0-x86_64-unknown-linux-gnu'](https://github.com/dojoengine/dojo/actions/runs/7477517467/job/20350589840?pr=1365) in `ci/clippy`, even though it's installed in the Dockerfile.

Don't we need to publish an updated version of the dev container to match the toolchain version bump? Because for the build, toolchains are automatically downloaded if not present on the system. But components may be adjusted in this case.

**Comment by glihm** [comment]
@kariy @tarrencev does something like this makes sense #1411?

The idea is to be able to push some devcontainer updates without directly relying on the `rust-toolchain` file, which may affect the whole building system, only to have the good version to release devcontainer (as it seems to be the case now).

Never made devcontainer release, I'm perhaps missing something.

WDYT?

**Comment by fishseabowl** [comment]
> > Hello @kariy, could you please take a look at the reported errors? It mentions that: [= note: the `wasm32-unknown-unknown` target may not be installed](https://github.com/dojoengine/dojo/actions/runs/7477517467/job/20350592794?pr=1365) in `ci/ensure-wasm`, and [error: 'cargo-clippy' is not installed for the toolchain '1.74.0-x86_64-unknown-linux-gnu'](https://github.com/dojoengine/dojo/actions/runs/7477517467/job/20350589840?pr=1365) in `ci/clippy`, even though it's installed in the Dockerfile.
> 
> Don't we need to publish an updated version of the dev container to match the toolchain version bump? Because for the build, toolchains are automatically downloaded if not present on the system. But components may be adjusted in this case.

@glihm Yes, the dev container will automatically match the rust-toolchain version, as shown in the following code: https://github.com/dojoengine/dojo/blob/3bb35a6790de3eea83e5c728ed0de46523a3de10/.devcontainer/Dockerfile#L19-L22
However, the `ci/wasm` and `ci/clippy` processes report errors related to uninstalled components, which seems strange.

**Comment by glihm** [comment]
> > > Hello @kariy, could you please take a look at the reported errors? It mentions that: [= note: the `wasm32-unknown-unknown` target may not be installed](https://github.com/dojoengine/dojo/actions/runs/7477517467/job/20350592794?pr=1365) in `ci/ensure-wasm`, and [error: 'cargo-clippy' is not installed for the toolchain '1.74.0-x86_64-unknown-linux-gnu'](https://github.com/dojoengine/dojo/actions/runs/7477517467/job/20350589840?pr=1365) in `ci/clippy`, even though it's installed in the Dockerfile.
> > 
> > 
> > Don't we need to publish an updated version of the dev container to match the toolchain version bump? Because for the build, toolchains are automatically downloaded if not present on the system. But components may be adjusted in this case.
> 
> @glihm Yes, the dev container will automatically match the rust-toolchain version, as shown in the following code:
> 
> https://github.com/dojoengine/dojo/blob/3bb35a6790de3eea83e5c728ed0de46523a3de10/.devcontainer/Dockerfile#L19-L22
> 
> However, the `ci/wasm` and `ci/clippy` processes report errors related to uninstalled components, which seems strange.

Yup, in the meantime, @fishseabowl could you try with this image? `glihm/dojo:1.74.0`
I just built it with the according toolchain version.

**Comment by tarrencev** [comment]
> @kariy @tarrencev does something like this makes sense #1411?
> 
> The idea is to be able to push some devcontainer updates without directly relying on the `rust-toolchain` file, which may affect the whole building system, only to have the good version to release devcontainer (as it seems to be the case now).
> 
> Never made devcontainer release, I'm perhaps missing something.
> 
> WDYT?

yup that makes sense!

**Comment by glihm** [comment]
@fishseabowl actually can you update with the new version of the dojo container?
https://github.com/dojoengine/dojo/pkgs/container/dojo-dev/165725993?tag=136a67a

**Comment by fishseabowl** [comment]
> @fishseabowl actually can you update with the new version of the dojo container? https://github.com/dojoengine/dojo/pkgs/container/dojo-dev/165725993?tag=136a67a

@glihm Yes. Done. Thank you for your help!

**Review by kariy — APPROVED** [review]

**Comment by glihm** [comment]
@fishseabowl do appreciate you've started all the work on this bump and identified the root reason.

The changes to the container triggered the auto PR that at the end is covering 100% of this PR. Apologize for that, I didn't had enough perspective to detect this earlier.

I'll close this one for now, thanking you again for the time dedicated to this.

**Pull request closed without merging**
