### PR TITLE
Extend component to describe schema

### PR DESCRIPTION
**Pull request by Cheelax**
fix issue https://github.com/dojoengine/dojo/issues/176

### CODE REVIEW

**Comment by Cheelax** [comment]
@tarrencev I think we are close to the end of the issue. Still two points:
-I am not sure it is possible right now to instanciate array with values like this: 
  `Array::new([
              ('x', 'felt252', 252),
              ('y', 'u32', 252),
              ('z', 'u64', 252),
          ])` as I have errors in the component diagnostics.
-Didn't find yet how to add the newline after each schema member, if you have any idea

**Comment by Cheelax** [comment]
Still tests to fix and fmt

**Comment by tarrencev** [comment]
> @tarrencev I think we are close to the end of the issue. Still two points: -I am not sure it is possible right now to instanciate array with values like this: `Array::new([ ('x', 'felt252', 252), ('y', 'u32', 252), ('z', 'u64', 252), ])` as I have errors in the component diagnostics. -Didn't find yet how to add the newline after each schema member, if you have any idea

Ah sorry i was using pseudo code in the example. Yeah for now you will need to construct and return the array manually, like

```
let schema_arr = array::ArrayTrait::new();
schema_arr.push(...)
schema_arr
```

**Comment by Cheelax** [comment]
@tarrencev lgtm
The only problem is that I didn't find a solution to pass the name in array.
We have in the view `fn schema() -> Array<(felt252, felt252, u8)>` instead of  ` fn schema() -> Array<(name, kind, len)>`

**Comment by Cheelax** [comment]
Dunno why the "system"is not passing though as I didn't touch it

**Comment by tarrencev** [comment]
lgtm. you'll have to regenerate the system test since it depends on components

**Review by tarrencev — APPROVED** [review]
good to merge once ci is passing

**Pull request merged**
