### PR TITLE
feat(saya): add config file arg for saya bin

### PR DESCRIPTION
**Pull request by Jonatan-Chaverri**
Closes issue #1504 
(WIP)

### CODE REVIEW

**Comment by Jonatan-Chaverri** [comment]
@glihm I start working on this issue, but need a few more details. First of all I want to make sure that I understood the issue correctly, can you please check the PR and let me know. 
Second is, does this JSON file should be in the project? If so, which path will be a good location for it. 
Thanks in advance.

**Comment by glihm** [comment]
Hey @Jonatan-Chaverri! Thank you for the contribution. :rocket: 

> I start working on this issue, but need a few more details.

Awesome, would you mind commenting on the issue, in order to assign it to you?

> First of all I want to make sure that I understood the issue correctly, can you please check the PR and let me know.

Yup! You're on the right track! This is what we want, having a one file configuration to load the `SayaConfig`. As the configuration of the different components will evolve and may be somehow relatively "big", such file can help a lot.

From what's I've seen, here could be the following steps:
1. Adding the support for serde on `SayaConfig`.
2. Error handling on the JSON loading.
3. Adding some tests to ensure the correct behavior.

> Second is, does this JSON file should be in the project? If so, which path will be a good location for it.

You will definitely need to commit at least 1 configuration for testing. We may also include an example configuration file (additionally to the tests files), yes.

> Thanks in advance.

Thank to you, let's do it! :)

**Comment by glihm** [comment]
As it's a WIP, I converted it into a draft, feel free to reach out if you have any question or need some feedback!

**Comment by Jonatan-Chaverri** [comment]
@glihm please take a look at the changes and let me know what you think. Thanks.

**Comment by glihm** [comment]
> @glihm please take a look at the changes and let me know what you think. Thanks.

The design chosen for the genesis work required more flexibility on how the content of the JSON is processed. In the case of Saya's configuration file, it will only contains simple values.

Would you mind proposing a new commit where only `serde` and `serde_json` are used without introducing new types?

Don't hesitate if you've doubt on how to achieve this.

**Comment by Jonatan-Chaverri** [comment]
@glihm ok, implemented the requested changes, please check again. Thanks.

**Comment by glihm** [comment]
Looks good thank you for the update!

1. You can remove the example file since we have the test file, it should be fine for now.
2. Could you ensure you've run the scripts like `bash scripts/rust_fmt.sh` and `bash scripts/clippy.sh`.
3. We may add a comment in the help to explicitly say that the config file takes precedence over every other CLI arguments.

**Comment by glihm** [comment]
Also could we use the default katana url please? `http://localhost:5050`. Thanks!

**Comment by Jonatan-Chaverri** [comment]
@glihm done! Please check again. Thanks.

**Comment by glihm** [comment]
Hey @Jonatan-Chaverri thanks for the update.
To ensure you're prepared for the CI, don't hesitate to run locally:

```
cargo nextest run --all-features
```

If everything goes well, it should be fine for the CI as well. Could you please have a look?

**Comment by Jonatan-Chaverri** [comment]
@glihm now its ready to pass the CI. The major change I did was to add a deserialize function for URL. Please check again. Thanks.

**Comment by glihm** [comment]
@Jonatan-Chaverri awesome, thank you for the work done here!

I've pushed some minor fixes, one due to celestia namespace limit, and the other one to ensure `rpc-url` is always given (but optional). Which allows one to do:
```
saya --config-file ./path/config.json
```
without having to give `--rpc-url`, which is non optional. :+1:

**Review by glihm — APPROVED** [review]
@Jonatan-Chaverri good work and welcome to the dojo! :)

Some comments about the flow you experienced with the PR:
1. Avoid to do `--force` with your push. Even if you have to iterate it's not a problem and sometimes it's better to have the historical changes to understand some decisions.
2. CI is an ally, not an enemy. It's good practice to run the scripts that are used by the CI locally to ensure you're not forgetting something.
3. Appreciate your patience and time dedicated to this contribution. <3

**Pull request merged**
