### PR TITLE
feat(libp2p): command to wait for the relay to be ready

### PR DESCRIPTION
**Pull request by Larkooo**
adds a command for the client to wait for the relay server to be ready. in cases where the client wants to make sure the relay is listening before trying to publish a message

### CODE REVIEW

**Review by glihm — COMMENTED** [review]
@Larkooo should we consider a timeout here, or the client should not be stuck in such situation?

**Comment by Larkooo** [comment]
> @Larkooo should we consider a timeout here, or the client should not be stuck in such situation?

what do you mean by a timeout? like a naive approach where we wait a specific amount of time?
it wouldn't be sustainable because clients might act differently from others, for eg. the wasm client takes more time to receive a handshake from the relay server than a native platform client. also imo we don't want to block clients -  because in a game it would just be completely blocking and potentially introduce a freeze

**Comment by Larkooo** [comment]
and also the waiting is needed only for publishing messages - to make sure that the relay server is ready to receive it so we dont lose a message if we try to publish it and the relay server is not ready yet

**Review by glihm — APPROVED** [review]
Got you, thanks the context.

Perhaps for a subsequent PR we can specify a channel we are waiting the subscription from.
As for now any subscribed event will define the state as ready. I don't know the exact use case in client side you're having, it's in our case enough I guess?

**Comment by Larkooo** [comment]
> Perhaps for a subsequent PR we can specify a channel we are waiting the subscription from.

Oh yeah basically, the Subscribed event is only supposed to be coming from the relay server because that event is emitted when a remote peer subscribes to a channel, and the only remote peer we have is the relay server (yes it's weird but it's because the server acts as a relay). So basically for now it's safe to just assume that any subscription event we receive means that the server is ready - because we received its subscription confirmation (to the topic where our message is going to be broadcasted)

**Pull request merged**
