### PR TITLE
validate cairo compiler version with manifest file

### PR DESCRIPTION
**Pull request by 0xicosahedron**
Fixes: #963

### CODE REVIEW

**Comment by tarrencev** [comment]
Can we add a test here?

**Comment by 0xicosahedron** [comment]
@tarrencev added an integration tests similar to test for `init`, any other test needed?

**Comment by 0xicosahedron** [comment]
i think test is failing because the path i specified is relative which depends on where the test is ran from

**Comment by 0xicosahedron** [comment]
not sure why exactly it failed, but as per docs i have tried to canonicalize the path before passing it in. it was and still working for me locally

**Comment by 0xicosahedron** [comment]
@tarrencev CI failure are coming from part of code that i haven't changed, any ideas why?

**Comment by 0xicosahedron** [comment]
lol just noticed `data` directory which contained the test project was ignored by `.gitignore` , renamed it to `test_data`

**Comment by 0xicosahedron** [comment]
any more blockers?

**Comment by tarrencev** [comment]
> any more blockers?

hey i just wanted to look into how `scarb::version::get()` works, do you know where it is getting the version from? if it is from the scarb binary, then i think this check wont work, since dojo bundles its own scarb instance

**Comment by 0xicosahedron** [comment]
its not from binary, see: https://github.com/software-mansion/scarb/blob/f803c6c673bc6d60f049871d21a15dec1c06e7ae/scarb/src/version.rs#L124-L148

although the constants mentioned are being read from environment variable which are added in `build.rs`, so the pipeline is a bit complicated. but afaik understand build system if anything changes in scarb `build.rs` is ran so the values should be as expected.

**Comment by tarrencev** [comment]
ok cool i think that works well!

**Pull request merged**
