### PR TITLE
feat(sozo): add support for v3 transactions

### PR DESCRIPTION
**Pull request by lambda-0x**

### CODE REVIEW

**Comment by kariy** [comment]
not necessarily blocked, but katana is yet to fully support v3 transactions due to no STRK token declared ref #2405

**Comment by glihm** [comment]
@lambda-0x since @kariy merged the STRK token, when core will be merged let's rebase this one to unlock v3.

As @kariy mentioned if by default we could have sozo choosing the token that has balance, it could be great for UX. But we should keep a simple way with a flag to actually chose the token to use.

**Comment by glihm** [comment]
@lambda-0x if you still want to tackle this, with the `rc.0` should be much simpler for the invoker. Just about how the token fee is carried by the transaction config.

**Comment by glihm** [comment]
Simplified in #2650.

**Pull request closed without merging**
